language: php

php:
  - "5.4"

before_script:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always