language: php

php:
  - "5.5"

before_script:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
