language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"

env:
  matrix:
# As new versions of mediawiki are released they should be added to the matrix
    - MW=master DBTYPE=sqlite
    - MW=master DBTYPE=mysql

before_script:
  - set -x
  - originalDirectory=$(pwd)
  - cd ..
  - wget https://github.com/wikimedia/mediawiki-core/archive/$MW.tar.gz
  - tar -zxf ${MW}.tar.gz
  - mv mediawiki-core-${MW} mediawiki-core
  - cd mediawiki-core
  - export MW_INSTALL_PATH=$(pwd)
  - mysql -e 'create database its_a_mw;'
  - php maintenance/install.php --dbtype ${DBTYPE} --dbuser root --dbname its_a_mw --dbpath $(pwd) --pass nyan TravisWiki admin
  - cd extensions
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Scribunto.git --depth 1
  - cp -r ${originalDirectory} Wikidata
  - cd ..
  
  - echo 'error_reporting(E_ALL| E_STRICT);' >> LocalSettings.php
  - echo 'ini_set("display_errors", 1);' >> LocalSettings.php
  - echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
  - echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php
  - echo '$wgLanguageCode = "'en'";' >> LocalSettings.php
  - echo "define( 'WB_EXPERIMENTAL_FEATURES', true );" >> LocalSettings.php
  
  - echo '$wgEnableWikibaseRepo = true;' >> LocalSettings.php
  - echo '$wgEnableWikibaseClient  = true;' >> LocalSettings.php
  - echo '$wmgUseWikibaseRepo  = true;' >> LocalSettings.php
  - echo '$wmgUseWikibaseClient  = true;' >> LocalSettings.php

  - echo 'require_once __DIR__ . "/extensions/Wikidata/Wikidata.php";' >> LocalSettings.php
  - echo 'require_once __DIR__ . "/extensions/Wikidata/extensions/Wikibase/repo/ExampleSettings.php";' >> LocalSettings.php
  - echo 'require_once __DIR__ . "/extensions/Scribunto/Scribunto.php";' >> LocalSettings.php
  
  - echo '$wgWBClientSettings["siteGlobalID"] = "enwiki";' >> LocalSettings.php
  
  - php maintenance/update.php --quick

script:
  - set -x
  - cd ../mediawiki-core/tests/phpunit
  - php phpunit.php --group Wikibase
